apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: 791945999903.dkr.ecr.us-east-1.amazonaws.com/aerolink/booking-service:45efaf572b63d8e9653f428f887693f9663595a4
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: AWS_REGION
              value: "us-east-1"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: default
spec:
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
