apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-service
  template:
    metadata:
      labels:
        app: flight-service
    spec:
      containers:
        - name: flight-service
          image: 791945999903.dkr.ecr.us-east-1.amazonaws.com/aerolink/flight-service:086a810fb1ac90a4f61c31d68a2bdb5504a63634
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: AWS_REGION
              value: "us-east-1"
---
apiVersion: v1
kind: Service
metadata:
  name: flight-service
  namespace: default
spec:
  selector:
    app: flight-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
